version: "3.9"
services:
  db_majoo_dev:
    image: mysql:8.0
    container_name: "db_majoo_dev"
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - mysql-data-dev:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d # create multiple database
    environment:
      MYSQL_USER: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: majoo
volumes:
  mysql-data-dev:
